preset: symfony

enabled:
  - no_useless_else
  - no_useless_return
  - ordered_class_elements
  - ordered_imports
  - phpdoc_order
  - short_array_syntax

disabled:
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_align
  - phpdoc_var_without_name
